server:
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
  port: 8080
  shutdown: graceful

management:
  info:
    git:
      enabled: true
      mode: full
  endpoint:
    shutdown:
      enabled: false
    beans:
      cache:
        time-to-live: 10s
    health:
      status:
        order:
          - fatal
          - down
          - out-of-service
          - unknown
          - up
        http-mapping:
          down: 503
          fatal: 503
          out-of-service: 503
    loggers:
      enabled: true
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: health,info
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
  file:
    name: ${LOG_FILE_NAMES:./logs/logger.log}
  config: classpath:log4j2-spring.xml

datasource:
  url: ${APP_DATABASE_URL:jdbc:mysql://localhost:3306/test}
  username: ${APP_DATABASE_USERNAME:test}
  password: ${APP_DATABASE_PASSWORD:test}
  hikari:
    driver-class-name: oracle.jdbc.OracleDriver
    minimum-idle: ${APP_DATABASE_IDLE_NUMBER_CONNECTION:10}
    maximum-pool-size: ${APP_DATABASE_POOL_SIZE:10}
    max-lifetime: ${APP_CONNECTION_MAX_LIFE_TIME:55000}
  liquibase:
    enabled: false